# Transient db - will lose it's data once restarted
version: "3"
services:
  postgres_next:
    image: postgres:11-alpine
    container_name: psql_next
    restart: always
    command: postgres -c 'max_connections=500'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: unsecured
      POSTGRES_DB: chinook
    ports:
      - "127.0.0.1:6432:5432"
    logging:
      options:
        max-size: 50m
        max-file: "3"
  postgraphile_next:
    image: postgraphile_next:latest
    container_name: postgraphile_next
    restart: always
    # PostGraphile uses the --max-pool-size setting *per worker*, so 133 * 3 = 399 connections
    command: postgraphile -c 'postgres://postgres:unsecured@postgres_next:5432/chinook' --host 0.0.0.0 --port 5091 --max-pool-size 133 --cluster-workers "3" --disable-query-log --simple-collections only
    ports:
      - "127.0.0.1:5091:5091"
    logging:
      options:
        max-size: 50m
        max-file: "3"
